[workspace]
members = ["oss-api", "oss-svr"]
resolver = "3"

[workspace.dependencies]
log = "0.4.28"
clap = "4.5.53"
chrono = "0.4.42"
serde = "1.0.228"
serde_with = "3.16.0"
serde_json = "1.0.145"
reqwest = "0.12.24"
tokio = "1.48.0"
actix-web = "4.12.0"
actix-multipart = "0.7.2"
sea-orm = "1.1.19"
sqlx = "0.8.6"
bytesize = "2.3.1"
regex = "1.12.2"
tempfile = "3.23.0"
once_cell = "1.21.3"
o2o = "0.5.4"
validator = "0.20.0"
strum = "0.27.2"
utoipa = "5.4.0"
utoipa-swagger-ui = "9.0.2"
idworker = "0.3.5"
wheel-rs = "0.4.1"
robotech = "0.11.0"

[patch.crates-io]
wheel-rs = { path = "../wheel-rs" }
robotech = { path = "../robotech-rs" }
