[workspace]
members = ["oss-api", "oss-svr"]
resolver = "3"

[workspace.dependencies]
log = "0.4.29"
clap = "4.5.54"
chrono = "0.4.42"
serde = "1.0.228"
serde_with = "3.16.1"
serde_json = "1.0.148"
reqwest = "0.13.1"
tokio = "1.49.0"
actix-web = "4.12.1"
actix-multipart = "0.7.2"
sea-orm = "1.1.19"
sqlx = "0.8.6"
bytesize = "2.3.1"
regex = "1.12.2"
tempfile = "3.24.0"
once_cell = "1.21.3"
o2o = "0.5.4"
validator = "0.20.0"
strum = "0.27.2"
utoipa = "5.4.0"
utoipa-swagger-ui = "9.0.2"
# cross打包时用，需要开启vendored feature
openssl = "0.10.75"
idworker = "0.3.5"
wheel-rs = "1.1.1"
robotech = "1.0.5"

[patch.crates-io]
wheel-rs = { path = "../wheel-rs" }
robotech = { path = "../robotech-rs" }
